language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
    fast_finish: true
    include:
        - php: 7.2
          env: SYMFONY_VERSION="4.*"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: ./vendor/bin/phpunit

sudo: false
