language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

matrix:
    fast_finish: true
    include:
        - php: 5.6
          env: COMPOSER_FLAGS="--prefer-lowest"
        - php: 5.6
          env: SYMFONY_VERSION=2.8.*
        - php: 5.6
          env: SYMFONY_VERSION="3.*"
        - php: 7.2
          env: SYMFONY_VERSION="4.*"

before_install:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;

install: composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script: ./vendor/bin/phpunit

sudo: false
